repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, css, scss, json]
        additional_dependencies:
          - prettier@3.1.0

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npm run lint
        language: system
        types: [javascript, jsx, ts, tsx]
        pass_filenames: false

      - id: typescript-check
        name: typescript-check
        entry: npm run type-check
        language: system
        types: [javascript, jsx, ts, tsx]
        pass_filenames: false
        stages: [push]

      - id: frontend-tests
        name: frontend-tests
        entry: npm test
        language: system
        pass_filenames: false
        stages: [push] 