runtime: custom
env: flex

service: frontend

env_variables:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://meeting-spot-backend-270814322595.us-east1.run.app"
  DEBUG: "*"
  NODE_DEBUG: "*"
  NODE_OPTIONS: "--trace-warnings --trace-uncaught"

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

vpc_access_connector:
  name: "projects/find-a-meeting-spot/locations/us-east1/connectors/meeting-spot-connector"

handlers:
  - url: /.*
    script: auto
    secure: always 