steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/meeting-spot-frontend:$COMMIT_SHA', 
           '--build-arg', 'NEXT_PUBLIC_API_URL_ARG=https://meeting-spot-backend-270814322595.us-east1.run.app/api',
           '.']
# ... rest of file 