# DISABLED: This workflow has been consolidated into unified-workflow.yml
name: Frontend CI/CD (Disabled)

on:
  # Disabling triggers
  push:
    branches: [ disabled ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Test and Build Steps
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm install
          
      - name: Run tests
        run: |
          npm test
          
      - name: Build
        run: |
          npm run build
          
      # Deployment Steps
      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        
      - name: Configure Docker
        run: gcloud auth configure-docker
        
      - name: Build and Push Frontend Container
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/meeting-spot-frontend:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/meeting-spot-frontend:${{ github.sha }}
          
      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy meeting-spot-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/meeting-spot-frontend:${{ github.sha }} \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated \
            --set-env-vars="NEXT_PUBLIC_API_URL=https://meeting-spot-backend-zylogyedtq-ue.a.run.app/api/v1" \
            --set-env-vars="NODE_ENV=production" \
            --port=8080 \
            --memory=512Mi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=10 \
            --concurrency=80 \
            --set-env-vars="DATABASE_URL=postgresql+pg8000://postgres:YOUR_ACTUAL_PASSWORD@/findameetingspot?unix_sock=/cloudsql/find-a-meeting-spot:us-east1:findameetingspot/.s.PGSQL.5432" \
            --set-env-vars="ENCRYPTION_KEY=your_32_bytes_encryption_key" \
            --set-env-vars="GOOGLE_MAPS_API_KEY=your_google_maps_api_key" 