# DISABLED: This workflow has been consolidated into unified-workflow.yml
name: E2E Tests (Disabled)

on:
  # Disabling triggers
  push:
    branches: [ disabled ]
  pull_request:
    branches: [ disabled ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  basic-tests:
    name: Run Basic E2E Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      
      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps chromium
      
      - name: Run basic Playwright test
        working-directory: frontend
        run: npm run e2e:basic
        env:
          BASE_URL: ${{ secrets.E2E_TEST_URL || 'https://findameetingspot.com' }}
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: basic-test-results
          path: frontend/test-results/
          retention-days: 30
  
  auth-tests:
    name: Run Authentication E2E Tests
    runs-on: ubuntu-latest
    needs: basic-tests
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      
      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps chromium
      
      - name: Run simple auth tests
        working-directory: frontend
        run: npm run e2e:auth
        env:
          BASE_URL: ${{ secrets.E2E_TEST_URL || 'https://findameetingspot.com' }}
      
      - name: Run auth journey test
        if: success() || failure() # Run even if previous step fails
        working-directory: frontend
        run: npm run e2e:journey
        env:
          BASE_URL: ${{ secrets.E2E_TEST_URL || 'https://findameetingspot.com' }}
      
      - name: Upload auth test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: auth-test-results
          path: frontend/test-results/
          retention-days: 30 