name: Meeting Spot Frontend Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm test
      
      - name: Build
        run: npm run build
  
  basic-e2e-tests:
    name: Basic E2E Tests
    needs: test-and-build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      
      - name: Run basic Playwright test
        run: npm run e2e:basic
        env:
          BASE_URL: ${{ secrets.E2E_TEST_URL || 'https://findameetingspot.com' }}
      
      - name: Run db-check endpoint test
        run: npm run e2e:dbcheck
        env:
          BASE_URL: ${{ secrets.E2E_TEST_URL || 'https://findameetingspot.com' }}
        continue-on-error: true # Don't fail the workflow if this test fails
      
      - name: Run API diagnostics tests
        run: npm run e2e:api-diag
        env:
          BASE_URL: ${{ secrets.E2E_TEST_URL || 'https://findameetingspot.com' }}
        continue-on-error: true # Don't fail the workflow if these tests fail
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: basic-e2e-test-results
          path: ./test-results/
          retention-days: 30
  
  auth-e2e-tests:
    name: Authentication E2E Tests
    needs: basic-e2e-tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      
      - name: Run auth tests
        run: npm run e2e:auth
        env:
          BASE_URL: ${{ secrets.E2E_TEST_URL || 'https://findameetingspot.com' }}
      
      - name: Run auth journey test
        if: success() || failure() # Run even if previous step fails
        run: npm run e2e:journey
        env:
          BASE_URL: ${{ secrets.E2E_TEST_URL || 'https://findameetingspot.com' }}
      
      - name: Upload auth test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: auth-e2e-test-results
          path: ./test-results/
          retention-days: 30
  
  critical-path-e2e-tests:
    name: Critical Path E2E Tests
    needs: auth-e2e-tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      
      - name: Run critical path tests
        run: npm run e2e:critical-path
        env:
          BASE_URL: ${{ secrets.E2E_TEST_URL || 'https://findameetingspot.com' }}
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      
      - name: Upload critical path test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: critical-path-test-results
          path: ./test-results/
          retention-days: 30
  
  deploy:
    name: Deploy to Cloud Run
    # Only deploy on push to main (skip for PRs)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test-and-build, basic-e2e-tests, auth-e2e-tests, critical-path-e2e-tests]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Configure Docker
        run: gcloud auth configure-docker
      
      - name: Build and Push Frontend Container
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/meeting-spot-frontend:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/meeting-spot-frontend:${{ github.sha }}
      
      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy meeting-spot-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/meeting-spot-frontend:${{ github.sha }} \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated \
            --set-env-vars="NEXT_PUBLIC_API_URL=https://api.findameetingspot.com/api/v1" \
            --set-env-vars="NODE_ENV=production" \
            --port=8080 \
            --memory=512Mi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=10 \
            --concurrency=80 